# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true

minApprovals:
  MEMBER: 0
  COLLABORATOR: 1
maxRequestedChanges:
  NONE: 0
blockingLabels:
  - blocked

requiredBaseBranches:
  - master

# Pull requests will only be automatically merged when all of these reviewers have approved the
# pull request.
requiredReviewers:
  - ox-bot-approver

# Will merge whenever the above conditions are met, but also
# the owner has approved or merge label was added.
rules:
  - minApprovals:
      OWNER: 0
      MEMBER: 0
      COLLABORATOR: 1

mergeCommitMessage: "{title} (#{number})"
